version: '3.4'

services:
  erpclient:
    image: erpclient
    build:
      context: erp-client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8082:8082
